global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mlops-taxi-api"
    static_configs:
      - targets:
          [
            "af123ca0e408c475692506602c656aa8-216589427.us-east-1.elb.amazonaws.com:80",
          ]
